# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '11.3'
    use_frameworks!
  
    pod 'MaterialComponents/BottomAppBar'
    pod 'MaterialComponents/BottomAppBar+ColorThemer'
    pod 'MaterialComponents/Buttons'
    pod 'MaterialComponents/Buttons+ButtonThemer'
    pod 'Material', '~> 3.1.6'
    pod 'BEMCheckBox'

  # Pods for iosApp

  target 'iosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'share' do
  use_frameworks!

  # Pods for share

end
